services:
  anythingllm:
    image: mintplexlabs/anythingllm:latest
    container_name: anythingllm
    ports:
    - "3001:3001"
    cap_add:
      - SYS_ADMIN
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
    # Adjust for your environment
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET="4fA3b5E8cD9jK2lMpQ0rS"
      - LLM_PROVIDER=ollama
      - "OLLAMA_BASE_PATH=http://host.docker.internal:11434"
      - OLLAMA_MODEL_PREF="deepseek-r1:7b"
      - OLLAMA_MODEL_TOKEN_LIMIT=4096
      - EMBEDDING_ENGINE=ollama
      - "EMBEDDING_BASE_PATH=http://host.docker.internal:11434"
      - EMBEDDING_MODEL_PREF=quentinz/bge-large-zh-v1.5:latest 
      - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=512
      - VECTOR_DB=lancedb
      - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8
      - AGENT_SERPER_DEV_KEY="SERPER DEV API KEY"
      - AGENT_SERPLY_API_KEY="Serply.io API KEY"
    volumes:
      - anythingllm_storage:/app/server/storage
    restart: always

volumes:
  anythingllm_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./storage
