version: '3'

services:
  maxkb:
    image: registry.fit2cloud.com/maxkb/maxkb
    container_name: maxkb
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./maxkb:/var/lib/postgresql/data
      - ./python-packages:/opt/maxkb/app/sandbox/python-packages