
# n8n - 工作流自动化平台
# 数据存储在当前目录的 data 文件夹中

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"  # Web UI 端口
    volumes:
      - ./data:/home/node/.n8n  # 数据持久化到本地 data 目录
      - ./Work/python/playwright-lawenforcement:/home/scan-folder # 需要扫描的目录
    environment:
      # 基本配置
      - N8N_HOST=${N8N_HOST:-localhost}  # n8n 主机名 
      - N8N_PORT=5678                    # n8n 端口
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}  # 协议 (http 或 https)
      - NODE_ENV=production              # 生产环境模式
      - WEBHOOK_URL=${WEBHOOK_URL:-}     # Webhook URL (可选)
      
      # 时区设置
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Asia/Shanghai}
       
      # 执行设置
      - EXECUTIONS_PROCESS=${EXECUTIONS_PROCESS:-main}  # 执行流程模式
      - EXECUTIONS_TIMEOUT=${EXECUTIONS_TIMEOUT:-120}   # 执行超时时间(秒)
      - EXECUTIONS_TIMEOUT_MAX=${EXECUTIONS_TIMEOUT_MAX:-3600}  # 最大执行超时时间
      
      # 安全设置 (可选)
      # - N8N_BASIC_AUTH_ACTIVE=true      # 启用基本认证
      # - N8N_BASIC_AUTH_USER=user       # 基本认证用户名
      # - N8N_BASIC_AUTH_PASSWORD=pass   # 基本认证密码
      
      # 数据库配置 (默认使用 SQLite，可选配置 PostgreSQL)
      # - DB_TYPE=postgresdb
      # - DB_POSTGRESDB_HOST=postgres
      # - DB_POSTGRESDB_PORT=5432
      # - DB_POSTGRESDB_DATABASE=n8n
      # - DB_POSTGRESDB_USER=n8n
      # - DB_POSTGRESDB_PASSWORD=n8n
    # 如果需要使用 PostgreSQL 数据库，取消下面的注释
    # depends_on:
    #   - postgres

  # PostgreSQL 数据库 (可选)
  # postgres:
  #   image: postgres:13
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=n8n
  #     - POSTGRES_PASSWORD=n8n
  #     - POSTGRES_DB=n8n
  #     - POSTGRES_NON_ROOT_USER=n8n
  #   volumes:
  #     - ./db-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  
  # Redis 缓存 (可选，用于提高性能)
  # redis:
  #   image: redis:6-alpine
  #   restart: always
  #   volumes:
  #     - ./redis-data:/data
