# compose.yaml — proxy-only by default; TUN is an advanced override
services:
  metacubexd:
    image: ghcr.io/metacubex/metacubexd-server:latest
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - '18080:8080'
      - '9090:9090'
      - '7890:7890'
    environment:
      # CONTROL_TOKEN: 'change-me-control'
      #CLASH_SECRET: 'change-me-clash'
      CONTROL_PORT: '18080'
      CLASH_API_PORT: '9090'
      MIXED_PORT: '7890'
      TZ: 'Asia/Shanghai'
    volumes:
      - './clash:/data'
