version: "3"

services:
  mavenrepository:
    image: dzikoysk/reposilite:3.5.14
    container_name: mavenrepo
    volumes:
      - ./repository:/app/data
    ports:
      - "18090:8080"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx128m ${JAVA_COMPOSE_OPTS}
      - REPOSILITE_OPTS=--token admin:Aisino@2024
    restart: unless-stopped
    stdin_open: true
    tty: true

